name: Publish

on:
  push:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Test and Publish
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'v21'
          registry-url: https://npm.pkg.github.com/
          scope: '@ArnarTB'

      - name: Install Dependencies
        run: npm i
        
      - name: publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}


      
